package jeda00.adventura.core.events;

import jeda00.adventura.support.Response;

/**
 * Indicates that command was executed and returned response
 */
public class CommandExecutedEvent {

    private String command;

    private Response response;

    public CommandExecutedEvent(String command, Response response) {
        this.command = command;
        this.response = response;
    }

    /**
     * Returns command which was executed
     */
    public String getCommand() {
        return command;
    }

    /**
     * Returns response which was generated by the executed command
     */
    public Response getResponse() {
        return response;
    }

}
